[package]
name = "Nearssage"
description = "Talk with random people nearby ğŸ“"
version = "0.0.1"
edition = "2021"

[dependencies]
nearssage_commons = { path = "./commons" }
nearssage_server = { path = "./server" }

[workspace]
# members = ["commons", "protocol", "server"]
members = ["commons", "server"]

[profile.release]
lto = true

[profile.dev]
opt-level = 3
lto = "thin"
