[package]
name = "Nearssage"
description = "Talk with random people nearby ğŸ“"
version = "0.0.1"
edition = "2021"

[workspace]
members = ["commons", "protocol", "server", "client"]

[profile.release]
lto = true

[profile.dev]
opt-level = 1
